#Gunārs Hildebrants
print('Sekos tukša rinda')
print()
print('Visi ',end='')
print('Vārdi ',end='')
print('Vienā ',end='')
print('Rindā ')
print('Visi ',end='')
print('Vārdi ',end='')
print('Vienā ',end='')
print('Rindā ')
print('NO zvaigznītēm * veidots trijstūris')
print('  *  ')
print(' * * ')
print('*****')